# (A) Having a Look at Data

In [1]:
import numpy as np 
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

# View all columns of a dataframe
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

## 00. HSCP (Health and Social Care Partnership) \& HB (Health Board) Data

In [2]:
hscp_df = pd.read_csv("../rawdata/hscp16_hscp19.csv")
hscp_df.sample(5)

,HSCP,HSCPName,HSCPDateEnacted,HSCPDateArchived,HB,HBName,HBDateEnacted,HBDateArchived,Country
42,S37000035,North Lanarkshire,20190401,NaN,S08000032,NHS Lanarkshire,20190401,NaN,S92000003
3,S37000003,Angus,20160401,NaN,S08000030,NHS Tayside,20180202,NaN,S92000003
30,S37000025,Scottish Borders,20160401,NaN,S08000016,NHS Borders,20140401,NaN,S92000003
17,S37000014,Fife,20160401,20180201.0,S08000018,NHS Fife,20140401,20180201.0,S92000003
14,S37000011,East Renfrewshire,20151007,NaN,S08000031,NHS Greater Glasgow and Clyde,20190401,NaN,S92000003

| Column            | Type    | Label |
|-------------------|---------|-------|
| HSCP              | text    | Health and Social Care Partnership 2016 Code (revised in 2018 & 2019) |
| HSCPName          | text    | Name of the Health and Social Care Partnership 2016 (revised in 2018 & 2019) |
| HSCPDateEnacted   | numeric | Date Health and Social Care Partnership Code was enacted |
| HSCPDateArchived  | numeric | Date Health and Social Care Partnership Code was archived |
| HB                | text    | Health Board 2014 Code (revised in 2018 & 2019) |
| HBName            | text    | Name of the Health Board 2014 (revised in 2018 & 2019) |
| HBDateEnacted     | numeric | Date Health Board Code was enacted |
| HBDateArchived    | numeric | Date Health Board Code was archived |
| Country           | text    | Country Code for Scotland |

In [3]:
hb_df = pd.read_csv("../rawdata/hb14_hb19.csv")
hb_df.sample(5)

,HB,HBName,HBDateEnacted,HBDateArchived,Country
16,S08000031,NHS Greater Glasgow and Clyde,20190401,NaN,S92000003
6,S08000021,NHS Greater Glasgow and Clyde,20140401,20190331.0,S92000003
11,S08000026,NHS Shetland,20140401,NaN,S92000003
15,S08000030,NHS Tayside,20180202,NaN,S92000003
4,S08000019,NHS Forth Valley,20140401,NaN,S92000003

| Column          | Type    | Label |
|-----------------|---------|-------|
| HB              | text    | Health Board 2014 Code (revised in 2018 & 2019) |
| HBName          | text    | Name of the Health Board 2014 (revised in 2018 & 2019) |
| HBDateEnacted   | numeric | Date Health Board Code was enacted |
| HBDateArchived  | numeric | Date Health Board Code was archived |
| Country         | text    | Country Code for Scotland |

There is no need of HB data because all the columns of it are perfectly available in HSCP data.

## 01. GP Practices Contact Details

In [4]:
gp_practices_contact_details_df = pd.read_csv("../rawdata/practice_contactdetails_oct2024-open-data.csv")
gp_practices_contact_details_df.sample(5)

,PracticeCode,GPPracticeName,PracticeListSize,AddressLine1,AddressLine2,AddressLine3,AddressLine4,Postcode,TelephoneNumber,PracticeType,Dispensing,HB,HSCP,DataZone,GPCluster
744,80010,Central Avenue Surgery,4314,Central Avenue Surgery,The Health Centre,6 Central Avenue,Ardrossan,KA22 7DX,01294 463 838,17J,,S08000015,S37000020,S01011253,Three Towns Cluster
388,46165,Dr S Ross,3936,Dr S Ross,Shettleston Health Centre,420 Old Shettleston Road,Glasgow,G32 7JZ,0141 531 6250,17J,,S08000031,S37000034,S01010147,NE - Baillieston/Shettleston
283,38027,Stromness Surgery,3054,Stromness Surgery,John Street,Stromness,Orkney,KW16 3AD,01856 850 205,17J,,S08000025,S37000022,S01011805,Orkney
670,70841,St Leonard's Medical Centre,8487,St Leonard's Medical Centre,145 Pleasance,Edinburgh,NaN,EH8 9RU,0131 668 4547,17J,,S08000024,S37000012,S01008681,Edinburgh South East - South
155,21505,Methilhaven Surgery,2570,Methilhaven Surgery,Wellesley Unit,Randolph Wemyss Memorial Hospital,"Buckhaven, Fife",KY8 1HU,01333 426 913,2C,,S08000029,S37000032,S01009619,Levenmouth

| Column Name          | Data Type | Description                                                 |
| -------------------- | --------- | ----------------------------------------------------------- |
| **PracticeCode**     | Numeric   | Unique five-digit GP Practice code.                         |
| **GPPracticeName**   | Text      | Name of the GP practice.                                    |
| **PracticeListSize** | Numeric   | Number of patients registered with the GP practice.         |
| **AddressLine1**     | Text      | First line of the GP practice address.                      |
| **AddressLine2**     | Text      | Second line of the GP practice address (optional).          |
| **AddressLine3**     | Text      | Third line of the GP practice address (optional).           |
| **AddressLine4**     | Text      | Fourth line of the GP practice address (optional).          |
| **Postcode**         | Text      | Postcode of the GP practice location.                       |
| **TelephoneNumber**  | Text      | Contact telephone number for the GP practice.               |
| **PracticeType**     | Text      | GP practice contract type (e.g., “17J”, “2C”).              |
| **Dispensing**       | Text      | Dispensing status (field discontinued as of Jan 2024).      |
| **HB**               | Text      | Health Board code of the GP practice.                       |
| **HSCP**             | Text      | Health and Social Care Partnership code of the GP practice. |
| **DataZone**         | Text      | 2011 Datazone code of the GP practice.                      |
| **GPCluster**        | Text      | GP Cluster group that the practice belongs to.              |

## 02. GP Contact Details

In [5]:
gp_contact_details_df = pd.read_csv("../rawdata/gp_contactdetails_oct2024-open-data.csv")
gp_contact_details_df.sample(5)

,GeneralMedicalCouncilNumber,GPDesignation,Forename,MiddleInitial,Surname,Sex,SexQF,PracticeCode,GPPracticeName,AddressLine1,AddressLine2,AddressLine3,AddressLine4,Postcode,Telephone,HB,HSCP
4643,7266432,PERFORMER REGISTRAR,Claire,NaN,Chestnutt,NaN,:,77055,Dalhousie Medical Practice,Dalhousie Medical Practice,The Health Centre,109-111 High Street,Bonnyrigg,EH19 2ET,0131 370 3999,S08000024,S37000018
430,7136161,PERFORMER SALARIED,Lucy,C,Sedgwick,Female,NaN,16211,The Tweed Practice,The Tweed Practice,Hay Lodge Health Centre,Neidpath Road,Peebles,EH45 8JG,01721 720 601,S08000016,S37000025
752,7266131,PERFORMER SALARIED,Claire,NaN,Lindsay,Female,NaN,20659,Cos Lane Surgery,Cos Lane Surgery,Woodside Road,Glenrothes,Fife,KY7 4AQ,01592 752 100,S08000029,S37000032
4941,4327114,PERFORMER SALARIED,Alison,H,Woods,Female,NaN,78429,Murieston Medical Practice LLP,Murieston Medical Practice LLP,Hamilton Square,Murieston South,Livingston,EH54 9JZ,01506 461 464,S08000024,S37000030
4576,7639750,PERFORMER REGISTRAR,Mark,P,Doyle,Male,NaN,76137,North Berwick Group Practice,North Berwick Group Practice,North Berwick Health Centre,54 St. Baldred's Road,North Berwick,EH39 4PU,01620 892 169,S08000024,S37000010

| Column                  | Type    | Description                                           |
|-------------------------|---------|-------------------------------------------------------|
| GeneralMedicalCouncilNumber | numeric | Unique registration number for medical practitioners |
| GPDesignation           | text    | Role or title of the GP (e.g., Performer, Registrar)  |
| Forename                | text    | First name of the GP                                  |
| MiddleInitial           | text    | Middle initial of the GP (if any)                     |
| Surname                 | text    | Last name of the GP                                   |
| Sex                     | text    | Gender of the GP (e.g., Male, Female)                 |
| SexQF                   | text    | Qualifier for Sex (additional info or notes)         |
| PracticeCode            | numeric | Five-digit code identifying the GP Practice          |
| GPPracticeName          | text    | Name of the GP Practice                               |
| AddressLine1            | text    | First line of the practice’s address                  |
| AddressLine2            | text    | Second line of the practice’s address                 |
| AddressLine3            | text    | Third line of the practice’s address                  |
| AddressLine4            | text    | Fourth line of the practice’s address                 |
| Postcode                | text    | Postal code of the practice location                   |
| Telephone               | text    | Contact telephone number of the practice              |
| HB                      | text    | Health Board code associated with the practice        |
| HSCP                    | text    | Health and Social Care Partnership code                |

## 03. GP Practices List Sizes

In [6]:
gp_practices_list_sizes_df = pd.read_csv("../rawdata/practice_listsizes_oct2024-open-data.csv")
gp_practices_list_sizes_df.sample(5)

,Date,PracticeCode,HB,HSCP,Sex,SexQF,AllAges,AllAgesQF,Ages0to4,Ages0To4QF,Ages5to14,Ages5To14QF,Ages15to24,Ages15To24QF,Ages25to44,Ages25To44QF,Ages45to64,Ages45To64QF,Ages65to74,Ages65To74QF,Ages75to84,Ages75To84QF,Ages85plus,Ages85PlusQF
1997,20241001,70662,S08000024,S37000012,All,d,19969.0,NaN,955.0,NaN,2663.0,NaN,2489.0,NaN,7801.0,NaN,4365.0,NaN,1077.0,NaN,478.0,NaN,141.0,NaN
2172,20241001,78062,S08000024,S37000030,Male,NaN,3370.0,NaN,161.0,NaN,382.0,NaN,416.0,NaN,965.0,NaN,921.0,NaN,291.0,NaN,193.0,NaN,41.0,NaN
1979,20241001,70588,S08000024,S37000012,All,d,8328.0,NaN,401.0,NaN,896.0,NaN,842.0,NaN,2792.0,NaN,2092.0,NaN,697.0,NaN,430.0,NaN,178.0,NaN
2039,20241001,70997,S08000024,S37000012,All,d,9714.0,NaN,330.0,NaN,820.0,NaN,720.0,NaN,4421.0,NaN,2138.0,NaN,748.0,NaN,400.0,NaN,137.0,NaN
336,20241001,18659,S08000017,S37000006,Male,NaN,2570.0,NaN,74.0,NaN,217.0,NaN,250.0,NaN,488.0,NaN,773.0,NaN,414.0,NaN,271.0,NaN,83.0,NaN

| Column        | Type    | Label |
|---------------|---------|-------|
| Date          | numeric | Date on which data was extracted |
| PracticeCode  | numeric | Five digit numeric GP Practice Code |
| HB            | text    | Health Board of the GP Practice |
| HSCP          | text    | Health and Social Care Partnership Code of the GP Practice |
| Sex           | text    | Sex of the registered patients as Male, Female or All |
| SexQF         | text    | Qualifier for Sex |
| AllAges       | numeric | Number of registered patients (all ages) |
| AllAgesQF     | text    | Qualifier for AllAges |
| Ages0to4      | numeric | Number of registered patients aged 0-4 years |
| Ages0To4QF    | text    | Qualifier for Ages0to4 |
| Ages5to14     | numeric | Number of registered patients aged 5-14 years |
| Ages5To14QF   | text    | Qualifier for Ages5to14 |
| Ages15to24    | numeric | Number of registered patients aged 15-24 years |
| Ages15To24QF  | text    | Qualifier for Ages15to24 |
| Ages25to44    | numeric | Number of registered patients aged 25-44 years |
| Ages25To44QF  | text    | Qualifier for Ages25to44 |
| Ages45to64    | numeric | Number of registered patients aged 45-64 years |
| Ages45To64QF  | text    | Qualifier for Ages45to64 |
| Ages65to74    | numeric | Number of registered patients aged 65-74 years |
| Ages65To74QF  | text    | Qualifier for Ages65to74 |
| Ages75to84    | numeric | Number of registered patients aged 75-84 years |
| Ages75To84QF  | text    | Qualifier for Ages75to84 |
| Ages85plus    | numeric | Number of registered patients aged 85 years and over |
| Ages85PlusQF  | text    | Qualifier for Ages85plus |

In [7]:
qualifier_lookup_df = pd.read_csv("../rawdata/statisticalqualifiers24052019.csv", encoding="cp1252")
qualifier_lookup_df.head(5)

,Qualifier,QualifierName,QualifierDefinition
0,b,break in time series,Break in a series of data occurring when there...
1,c,confidential,Where presentation of data would disclose conf...
2,†,earliest revision,A period for which the earliest revision was m...
3,e,estimated,The particular value yielded by an estimator i...
4,f,forecast,The statistical value is forecasted. It is not...

## 04. Disease Prevalence by GP Practice

In [9]:
disease_prevalence_gp_practice_df = pd.read_excel("../rawdata/diseaseprevalence_practice_total.xlsx", sheet_name="DP_Practice_total")
disease_prevalence_gp_practice_df.sample(10)

,GPPractice/Area,Year,Age,Sex,AreaType,PracticeCode,PatientCount_Asthma,PatientCount_Atrial Fibrillation,PatientCount_Cancer,PatientCount_Chronic Kidney Disease (CKD),PatientCount_Chronic Obstructive Pulmonary Disease (COPD),PatientCount_Coronary Heart Disease (CHD),PatientCount_Dementia,PatientCount_Depression,PatientCount_Diabetes,PatientCount_Eating Disorder,PatientCount_Epilepsy,PatientCount_Heart Failure,PatientCount_Hypertension,PatientCount_Mental Health,PatientCount_Osteoporosis,PatientCount_Palliative Care,PatientCount_Peripheral Arterial Disease (PAD),PatientCount_Rheumatoid Arthritis,PatientCount_Stroke and TIA,Change_Asthma,Change_Atrial Fibrillation,Change_Cancer,Change_Chronic Kidney Disease (CKD),Change_Chronic Obstructive Pulmonary Disease (COPD),Change_Coronary Heart Disease (CHD),Change_Dementia,Change_Depression,Change_Diabetes,Change_Eating Disorder,Change_Epilepsy,Change_Heart Failure,Change_Hypertension,Change_Mental Health,Change_Osteoporosis,Change_Palliative Care,Change_Peripheral Arterial Disease (PAD),Change_Rheumatoid Arthritis,Change_Stroke and TIA,Rate_Asthma,Rate_Atrial Fibrillation,Rate_Cancer,Rate_Chronic Kidney Disease (CKD),Rate_Chronic Obstructive Pulmonary Disease (COPD),Rate_Coronary Heart Disease (CHD),Rate_Dementia,Rate_Depression,Rate_Diabetes,Rate_Eating Disorder,Rate_Epilepsy,Rate_Heart Failure,Rate_Hypertension,Rate_Mental Health,Rate_Osteoporosis,Rate_Palliative Care,Rate_Peripheral Arterial Disease (PAD),Rate_Rheumatoid Arthritis,Rate_Stroke and TIA
33633,49604 - The Gordon Practice,2021,15-19,All,Practice,49604,15,0,0,0,0,0,0,10,5,0,5,0,0,0,0,0,0,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.4,0.0,0.0,0.0,0.0,0.0,0.0,3.6,1.8,0.0,1.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49113,63118 - Bothwell Medical Centre,2018,85plus,All,Practice,63118,10,32,25,76,20,61,15,10,25,0,0,15,109,0,5,0,10,5,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.3,16.9,13.2,40.2,10.6,32.3,7.9,5.3,13.2,0.0,0.0,7.9,57.7,0.0,2.6,0.0,5.3,2.6,13.8
2451,11306 - Broughty Family Healthcare,2021,00-04,All,Practice,11306,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2687,11645 - Mill Practice,2021,40-44,All,Practice,11645,38,0,5,0,5,5,0,39,20,0,25,0,28,15,0,0,0,0,0,31.0,NaN,0.0,NaN,0.0,NaN,NaN,5.4,0.0,-100.0,25.0,NaN,33.3,0.0,NaN,NaN,NaN,-100.0,NaN,7.6,0.0,1.0,0.0,1.0,1.0,0.0,7.8,4.0,0.0,5.0,0.0,5.6,3.0,0.0,0.0,0.0,0.0,0.0
37560,55075 - Dunbeath Surgery,2019,80-84,All,Practice,55075,5,10,5,10,0,10,5,0,5,0,0,5,21,0,0,0,5,0,5,NaN,0.0,0.0,0.0,NaN,0.0,NaN,NaN,0.0,NaN,NaN,0.0,5.0,NaN,NaN,NaN,NaN,NaN,0.0,18.5,37.0,18.5,37.0,0.0,37.0,18.5,0.0,18.5,0.0,0.0,18.5,77.8,0.0,0.0,0.0,18.5,0.0,18.5
41467,55662 - Acharacle Medical Practice,2021,05-09,All,Practice,55662,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26129,43167 - The Firhill Practice,2021,20-24,All,Practice,43167,20,0,0,0,0,0,0,42,5,5,0,0,0,0,0,0,0,0,0,-4.8,NaN,NaN,NaN,NaN,NaN,NaN,2.4,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,0.0,0.0,0.0,0.0,0.0,0.0,12.5,1.5,1.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11955,25686 - Allan Park Medical Practice,2020,20-24,All,Practice,25686,15,0,0,0,0,0,0,34,0,0,5,0,0,0,0,0,0,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,21.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.8,0.0,0.0,0.0,0.0,0.0,0.0,15.4,0.0,0.0,2.3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
54103,70501 - Murrayfield Medical Practice,2023,50-54,All,Practice,70501,37,0,20,0,0,0,0,5,5,5,5,0,43,5,0,0,0,5,5,5.7,-100.0,33.3,NaN,-100.0,NaN,NaN,-50.0,-50.0,0.0,0.0,NaN,30.3,0.0,NaN,NaN,NaN,0.0,0.0,7.4,0.0,4.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,8.5,1.0,0.0,0.0,0.0,1.0,1.0
20033,40027 - The Terrace Medical Practice,2018,35-39,All,Practice,40027,33,0,5,0,0,0,0,32,5,5,5,0,5,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,0.0,1.1,0.0,0.0,0.0,0.0,6.8,1.1,1.1,1.1,0.0,1.1,0.0,0.0,0.0,0.0,0.0,0.0

| Column | Type | Description |
| --- | --- | --- |
| GPPractice/Area | text | Name or description of the GP practice or area. |
| Year | numeric | Year for which the data is recorded. |
| Age | text | Age group of patients (e.g., 30-34, All). |
| Sex | text | Sex of patients (e.g., Male, Female, All). |
| AreaType | text | Type of area (e.g., Practice, Board). |
| PracticeCode | text | Unique code assigned to the GP practice. |
| PatientCount_Asthma | numeric | Number of patients diagnosed with Asthma. |
| PatientCount_Atrial Fibrillation | numeric | Number of patients diagnosed with Atrial Fibrillation. |
| PatientCount_Cancer | numeric | Number of patients diagnosed with Cancer. |
| PatientCount_Chronic Kidney Disease (CKD) | numeric | Number of patients diagnosed with Chronic Kidney Disease. |
| PatientCount_Chronic Obstructive Pulmonary Disease (COPD) | numeric | Number of patients diagnosed with Chronic Obstructive Pulmonary Disease. |
| PatientCount_Coronary Heart Disease (CHD) | numeric | Number of patients diagnosed with Coronary Heart Disease. |
| PatientCount_Dementia | numeric | Number of patients diagnosed with Dementia. |
| PatientCount_Depression | numeric | Number of patients diagnosed with Depression. |
| PatientCount_Diabetes | numeric | Number of patients diagnosed with Diabetes. |
| PatientCount_Eating Disorder | numeric | Number of patients diagnosed with Eating Disorders. |
| PatientCount_Epilepsy | numeric | Number of patients diagnosed with Epilepsy. |
| PatientCount_Heart Failure | numeric | Number of patients diagnosed with Heart Failure. |
| PatientCount_Hypertension | numeric | Number of patients diagnosed with Hypertension. |
| PatientCount_Mental Health | numeric | Number of patients diagnosed with Mental Health conditions. |
| PatientCount_Osteoporosis | numeric | Number of patients diagnosed with Osteoporosis. |
| PatientCount_Palliative Care | numeric | Number of patients receiving Palliative Care. |
| PatientCount_Peripheral Arterial Disease (PAD) | numeric | Number of patients diagnosed with Peripheral Arterial Disease. |
| PatientCount_Rheumatoid Arthritis | numeric | Number of patients diagnosed with Rheumatoid Arthritis. |
| PatientCount_Stroke and TIA | numeric | Number of patients diagnosed with Stroke or Transient Ischemic Attack. |
| Change_Asthma | numeric | Percentage change in Asthma patients compared to previous period. |
| Change_Atrial Fibrillation | numeric | Percentage change in Atrial Fibrillation patients compared to previous period. |
| Change_Cancer | numeric | Percentage change in Cancer patients compared to previous period. |
| Change_Chronic Kidney Disease (CKD) | numeric | Percentage change in Chronic Kidney Disease patients compared to previous period. |
| Change_Chronic Obstructive Pulmonary Disease (COPD) | numeric | Percentage change in COPD patients compared to previous period. |
| Change_Coronary Heart Disease (CHD) | numeric | Percentage change in CHD patients compared to previous period. |
| Change_Dementia | numeric | Percentage change in Dementia patients compared to previous period. |
| Change_Depression | numeric | Percentage change in Depression patients compared to previous period. |
| Change_Diabetes | numeric | Percentage change in Diabetes patients compared to previous period. |
| Change_Eating Disorder | numeric | Percentage change in Eating Disorder patients compared to previous period. |
| Change_Epilepsy | numeric | Percentage change in Epilepsy patients compared to previous period. |
| Change_Heart Failure | numeric | Percentage change in Heart Failure patients compared to previous period. |
| Change_Hypertension | numeric | Percentage change in Hypertension patients compared to previous period. |
| Change_Mental Health | numeric | Percentage change in Mental Health patients compared to previous period. |
| Change_Osteoporosis | numeric | Percentage change in Osteoporosis patients compared to previous period. |
| Change_Palliative Care | numeric | Percentage change in Palliative Care patients compared to previous period. |
| Change_Peripheral Arterial Disease (PAD) | numeric | Percentage change in PAD patients compared to previous period. |
| Change_Rheumatoid Arthritis | numeric | Percentage change in Rheumatoid Arthritis patients compared to previous period. |
| Change_Stroke and TIA | numeric | Percentage change in Stroke and TIA patients compared to previous period. |
| Rate_Asthma | numeric | Prevalence rate of Asthma (per 100 patients, or similar metric). |
| Rate_Atrial Fibrillation | numeric | Prevalence rate of Atrial Fibrillation. |
| Rate_Cancer | numeric | Prevalence rate of Cancer. |
| Rate_Chronic Kidney Disease (CKD) | numeric | Prevalence rate of Chronic Kidney Disease. |
| Rate_Chronic Obstructive Pulmonary Disease (COPD) | numeric | Prevalence rate of COPD. |
| Rate_Coronary Heart Disease (CHD) | numeric | Prevalence rate of CHD. |
| Rate_Dementia | numeric | Prevalence rate of Dementia. |
| Rate_Depression | numeric | Prevalence rate of Depression. |
| Rate_Diabetes | numeric | Prevalence rate of Diabetes. |
| Rate_Eating Disorder | numeric | Prevalence rate of Eating Disorders. |
| Rate_Epilepsy | numeric | Prevalence rate of Epilepsy. |
| Rate_Heart Failure | numeric | Prevalence rate of Heart Failure. |
| Rate_Hypertension | numeric | Prevalence rate of Hypertension. |
| Rate_Mental Health | numeric | Prevalence rate of Mental Health conditions. |
| Rate_Osteoporosis | numeric | Prevalence rate of Osteoporosis. |
| Rate_Palliative Care | numeric | Prevalence rate of Palliative Care patients. |
| Rate_Peripheral Arterial Disease (PAD) | numeric | Prevalence rate of PAD. |
| Rate_Rheumatoid Arthritis | numeric | Prevalence rate of Rheumatoid Arthritis. |
| Rate_Stroke and TIA | numeric | Prevalence rate of Stroke and TIA. |

## 05. GP Activity by HB

In [10]:
gp_activity_hb_df = pd.read_excel("../rawdata/data-may2025.xlsx", sheet_name="tab6final")
gp_activity_hb_df.sample(10)

,MonthYear,Geography,HCPGroup,EncounterClass,EncounterGroup,Count,DNA
56390,2021-09-01,NHS Orkney,Other Clinicians,Direct,Video Consultation,8,0
187932,2020-04-01,Dumfries and Galloway,Administration,Indirect,Medicines Management,2264,0
99973,2024-08-01,NHS Forth Valley,Students,Indirect,Secondary Care / Other NHS admin (Administration),0,0
61175,2022-01-01,NHS Highland,Students,Direct,Video Consultation,0,0
15914,2019-01-01,NHS Lanarkshire,Students,Undefined,Other,0,0
195299,2020-06-01,Scottish Borders,Unmapped,Undefined,Other,0,0
44004,2020-11-01,NHS Tayside,Unmapped,Indirect,Clinical Administration,1,0
96969,2024-05-01,NHS Western Isles,GPs,Indirect,Clinical Administration,4120,18
134874,2018-09-01,Clackmannanshire and Stirling,Other Clinicians,Indirect,Clinical Administration,1969,37
23677,2019-07-01,NHS Shetland,Administration,External Direct,Community/ HB staff Contacts,0,0

The business logic of encounter groupings is explained in the following table. 

| Encounter Class       | Encounter Grouping                                   | Encounter Type                                                                                                                                                                                                                                                                                                                                                                                                                                                   | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|-----------------------|------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Direct                | Surgery consultation                                 | Follow-up/routine visit, Surgery consultation, Emergency consultation, Casualty Attendance, Third party consultation, Hospital admission & Minor injury service, Extended Hours                                                                                                                                                                                                                                                                                                                      | These encounter types involve a face-to-face contact between clinician and patient or third party relevant to a patient.                                                                                                                                                                                                                                                                                                                                                                     |
| Direct                | Telephone consultation                               | Telephone call to a patient, Telephone call from a patient, Telephone Consultation                                                                                                                                                                                                                                                                                                                                                                                                                     | These encounter types involve a contact between clinician and patient that is by telephone. This includes those initiated by the patient or by practice staff.                                                                                                                                                                                                                                                                                                                               |
| Direct                | Home Visit                                           | Acute visit, Children's home visit, Home Visit, Hotel Visit, Nursing home visit, Residential home visit                                                                                                                                                                                                                                                                                                                                                                                                | These encounter types involve a face-to-face contact between clinician and patient that is in a location external to practice premises such as a residential home.                                                                                                                                                                                                                                                                                                                           |
| Direct                | Clinic                                               | Clinic                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | These encounter types involve a face-to-face contact between clinician and patient for a specific clinic, such as diabetes, asthma, anti-coagulation (recognising that there may be variations in use which may indicate more likelihood of errors).                                                                                                                                                                                                                                           |
| Direct                | Video consultation                                  | Video consultation                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | These encounter types relate to consultation encounters between clinician and patient by video.                                                                                                                                                                                                                                                                                                                                                                                               |
| Direct                | eConsultation                                       | eConsultation                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | These encounter types relate to consultations between clinician and patient by econsultation, for example by email.                                                                                                                                                                                                                                                                                                                                                                           |
| Direct                | Triage                                               | Triage                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | These encounter types relate to patients being directed to the most appropriate member of the general practice team or other service.                                                                                                                                                                                                                                                                                                                                                         |
| Direct                | External direct                                      | Out of Hours/ outside Practice: Night visit Deputising service, Night visit Local rota, Night visit practice, Out of hours Practice, Out of hours Non Practice, Twilight Visit, Walk-in Centre, Co-op Telephone advice, Co-op Surgery Consultation, Co-op Home Visit, Night Visit                                                                                                                                                                                                                      | These encounter types relate to encounters between patients and other healthcare providers such as walk-in centres or out of hours services.                                                                                                                                                                                                                                                                                                                                                  |
| Direct                | Community/ HB staff Contacts                         | Community Clinic, Community Nursing Note, Community Nursing Report, Health Authority Entry, Health Visitor Note, Health Visitor Report                                                                                                                                                                                                                                                                                                                                                                 | Encounter types that specify use by Community Nursing or Health Visitor. This also includes Health Authority entries.                                                                                                                                                                                                                                                                                                                                                                        |
| Indirect              | Medicines Management                                 | Repeat Issue, Medicine Management, Non-consultation medication data                                                                                                                                                                                                                                                                                                                                                                                                                                     | These encounter types are specifically related to the issuing of prescriptions or to the management of medications.                                                                                                                                                                                                                                                                                                                                                                          |
| Indirect              | Secondary Care / other NHS admin (Administration)    | Discharge details, Letter from Outpatients, Hospital Admission, Day Case Report, GOS18 Report, NHS Direct Report, Hospital Inpatient Report, Initial Post Discharge Review, Referral Letter, Social Services Report                                                                                                                                                                                                                                                                                     | These encounter types relate to communications with secondary care or other services such as the out of hours services or social care. This covers both management of incoming communications including discharge summaries and the sending of letters and reports.                                                                                                                                                                                                                           |
| Indirect              | Investigation request / results (Administration)     | Laboratory Request, Radiology Request, Radiology Result                                                                                                                                                                                                                                                                                                                                                                                                                                                  | These encounter types relate to requests and incoming results, including from laboratories and radiology.                                                                                                                                                                                                                                                                                                                                                                                    |
| Indirect              | General Administration                               | Mail from patient, Mail to patient, Administration, Template Entry, Non-consultation data                                                                                                                                                                                                                                                                                                                                                                                                                | These encounter types cover administrative tasks not covered in other groupings, such as correspondence to and from patients, entry of data outside of consultations, or where the administrative task has not been defined.                                                                                                                                                                                                                                                                  |
| Indirect              | Clinical Administration                              | Mail from patient, Mail to patient, Administration, Template Entry, Non-consultation data                                                                                                                                                                                                                                                                                                                                                                                                                | These encounter types cover clinical administration tasks, relating to direct patient care, undertaken by clinical staff.                                                                                                                                                                                                                                                                                                                                                                    |
| External indirect     | In background, little direct interaction              | Data Transferred from other system, ePharmacy message, Results recording, MJOG                                                                                                                                                                                                                                                                                                                                                                                                                           | These are indirect encounter types that happen in the background with little or no intervention required by the practice. This includes GP2GP data transfers and ePharmacy message imports. This data is excluded from the activity dashboard. For these, if interventions are required, it is likely the staff member would open the records using other available encounter types.                                                                                                        |
| Undefined             | Other                                                | Undefined                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | These encounter types have yet to be mapped by the NCISS team. As the project progresses, EMIS Practices will be asked to map their “Undefined” encounter types and Vision practices will be asked to stop using the encounter type “Other”.                                                                                                                                                                                                                                                 |

## 06. Hospital Activity Data

In [11]:
diagnosis_codes_df = pd.read_csv("../rawdata/diagnosis_codes.csv")
diagnosis_codes_df.sample(5)

,ChapterCode,ChapterName,Condition,ICD10Codes
120,S00-T98,"Injury, poisoning and certain other consequenc...","Fracture of lower leg, including ankle",S82
62,"I84,K00-K93",Diseases of the digestive system,"Other diseases of oral cavity, salivary glands...",K09-K14
24,C00-D48,Neoplasms,Non-Hodgkin lymphoma,C82-C86
108,N00-N99,Diseases of the genitourinary system,Other disorders of breast including inflammato...,"N61-N62, N64"
33,D50-D89,Diseases of the blood and blood-forming organs...,Other diseases and disorders not classified above,Remainder of group

In [12]:
hospital_activity_by_council_2019_20_df = pd.read_excel("../rawdata/table-6-main-diagnosis-by-council-area-2023-24.xlsx", 
                                                        sheet_name="Data1")

hospital_activity_by_council_2020_21_df = pd.read_excel("../rawdata/table-6-main-diagnosis-by-council-area-2023-24.xlsx", 
                                                        sheet_name="Data2")

hospital_activity_by_council_2021_22_df = pd.read_excel("../rawdata/table-6-main-diagnosis-by-council-area-2023-24.xlsx", 
                                                        sheet_name="Data3")

hospital_activity_by_council_2022_23_df = pd.read_excel("../rawdata/table-6-main-diagnosis-by-council-area-2023-24.xlsx", 
                                                        sheet_name="Data4")

hospital_activity_by_council_2023_24_df = pd.read_excel("../rawdata/table-6-main-diagnosis-by-council-area-2023-24.xlsx", 
                                                        sheet_name="Data5")

In [13]:
display(hospital_activity_by_council_2019_20_df.sample(10))

display(hospital_activity_by_council_2020_21_df.sample(5))

display(hospital_activity_by_council_2021_22_df.sample(5))

display(hospital_activity_by_council_2022_23_df.sample(5))

display(hospital_activity_by_council_2023_24_df.sample(5))

,lookup,stays_Number,stays_Rate,los_stays_Number,los_stays_Rate,avlos_stays_Rate
249937,2019/20StirlingMale - 65+ yearsAll diagnoses (...,3358,40767.27,26964,327352.19,8.02978
157946,2019/20Na h-Eileanan SiarFemale - 70-74 yearsD...,0,0.00,5,565.61,NaN
28187,2019/20AngusAll Sexes - 90+ yearsType 2 diabet...,0,0.00,5,395.57,NaN
71185,2019/20East AyrshireAll Sexes - 35-39 yearsPer...,5,69.79,50,697.93,10.00000
131378,2019/20HighlandMale - 40-44 yearsOther anaemia...,5,77.50,0,0.00,0.00000
264265,2019/20West LothianFemale - 15-19 yearsPneumonia,0,0.00,0,0.00,0.00000
187333,2019/20Perth & KinrossFemale - All AgesAbdomin...,268,347.06,517,669.51,1.93000
107714,2019/20FalkirkMale - All AgesComplications of ...,296,375.39,3150,3994.88,10.64000
246955,2019/20StirlingFemale - 30-34 yearsAtrial fibr...,0,0.00,0,0.00,0.00000
204726,2019/20Resident of the Rest of United Kingdom ...,25,NaN,45,NaN,1.80000

,lookup,stays_Number,stays_Rate,los_stays_Number,los_stays_Rate,avlos_stays_Rate
33903,2020/21Argyll & ButeAll Sexes - 75-79 yearsOth...,5,114.57,10,229.15,2.00
116897,"2020/21Glasgow CityFemale - 75-79 yearsInjury,...",333,3900.67,5232,61286.17,15.71
64146,2020/21Dundee CityFemale - 50-54 yearsAngina p...,5,109.17,5,109.17,1.00
186908,2020/21RenfrewshireFemale - All AgesCholelithi...,204,220.28,780,842.24,3.82
213854,2020/21Shetland IslandsMale - 60-64 yearsDisea...,5,662.25,20,2649.01,4.00

,lookup,stays_Number,stays_Rate,los_stays_Number,los_stays_Rate,avlos_stays_Rate
145767,2021/22MorayAll Sexes - 45-49 yearsCoxarthrosi...,0,0.00,5,81.49,NaN
171327,2021/22North LanarkshireMale - 15-19 yearsAcut...,5,49.58,35,347.08,7.00
147658,2021/22MorayFemale - 0-4 yearsOther infectious...,48,2319.96,40,1933.30,0.83
202849,2021/22Scottish BordersFemale - 15-19 yearsOth...,0,0.00,0,0.00,0.00
45295,2021/22City of EdinburghMale - <18 yearsBurns ...,5,11.15,55,122.66,11.00

,lookup,stays_Number,stays_Rate,los_stays_Number,los_stays_Rate,avlos_stays_Rate
178338,2022/23Orkney IslandsFemale - 65-69 yearsDisea...,5,665.78,0,0.00,0.00
127686,2022/23HighlandFemale - 30-34 yearsOther disea...,10,149.72,30,449.17,3.00
19182,2022/23All Scottish and Non-Scottish Residents...,4370,80.22,11839,217.32,2.71
14935,2022/23AberdeenshireMale - 65-69 yearsMalignan...,0,0.00,35,438.93,NaN
184640,2022/23Perth & KinrossFemale - 60-64 yearsDise...,12,208.22,38,659.38,3.17

,lookup,stays_Number,stays_Rate,los_stays_Number,los_stays_Rate,avlos_stays_Rate
60388,2023/24pDumfries & GallowayMale - <18 yearsPoi...,15,116.31,10,77.54,0.67
155401,2023/24pNa h-Eileanan SiarAll Sexes - 75+ year...,108,3281.68,974,29595.87,9.02
173319,2023/24pNorth LanarkshireFemale - All AgesDise...,1814,1035.44,419,239.17,0.23
144708,2023/24pMidlothianFemale - All AgesAcute upper...,111,221.27,289,576.11,2.60
242691,2023/24pStirlingAll Sexes - 0-4 yearsOther inf...,54,1420.31,50,1315.10,0.93

<hr>